name: build

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          sudo apt install -y librime-dev
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Build
        run: |
          cargo build --release
